import streamlit as st
st.title(" Skills")
st.subheader(" Programming")
st.write("Python")
st.progress(77)
st.write("C++")
st.progress(30)
st.write("C")
st.progress(50)
st.write("JavaScript")
st.progress(77)
st.write("HTML/CSS")
st.progress(79)
st.subheader(" Design")
st.write("Canva / UI Design")
st.progress(90)
st.subheader(" Tools")
st.write("- GitHub")
st.write("- VS Code")
st.write("- Streamlit")